### ISSUE TITLE
City Guards: Stormwind

### ISSUE THREAD

**Issue by kaytotes** [kaytotes/NozdormuCore#18]
Using this issue as a general template for the rest of them since its a common issue but might as well be split into distinct parts.

The guards and many NPC's in the faction capital cities have a level that is too high as the are using the 3.3.5 levels and values. The easiest way to correct this would be to simply update the `creature_template` fields `min_level` and `max_level` for the entries of the guards. Should just trickle down for the various spawns but we'll need to double check that.

In this case at the very least the following need updating. Need to actually double check these ones in game first as i've not properly looked. Levels for guards should be 55 - 60ish. Use best judgement and if possible double check with a vanilla database where possible.

https://db.rising-gods.de/?npc=68
https://db.rising-gods.de/?npc=29088
https://db.rising-gods.de/?npc=29152
https://db.rising-gods.de/?npc=16396
https://db.rising-gods.de/?npc=29712
https://db.rising-gods.de/?npc=1756

**Comment by TaylorA-92** [comment]
More NPC's found in Stormwind of 60+ levels

**Comment by kaytotes** [comment]
https://db.rising-gods.de/?npc=1642

**Comment by TaylorA-92** [comment]
Issue resolved in:  https://github.com/kaytotes/NozdormuCore/pull/29/commits/cbe2586c9262be8916520b4329742b674509986c

- Major Mattingly and Field Marshal Afrasiabi already have the correct level

**Comment by kaytotes** [comment]
https://db.rising-gods.de/?npc=14438
https://db.rising-gods.de/?npc=29019
https://db.rising-gods.de/?npc=29154
https://db.rising-gods.de/?npc=29725
https://db.rising-gods.de/?npc=8383
https://db.rising-gods.de/?npc=352

**Comment by TaylorA-92** [comment]
Solved in https://github.com/kaytotes/NozdormuCore/pull/48/commits/603f9dfaa75d5d890700fcefd3d5d4c056aac80e
