### ISSUE TITLE
Stormwind War Mount Quartermaster Elekk

### ISSUE THREAD

**Issue by kaytotes** [kaytotes/NozdormuCore#34]
Lieutenant Karter sels the Reins of the Black War Elekk and shouldn't until TBC.

![image](https://cloud.githubusercontent.com/assets/7526918/25298443/ab4b8e2e-26ec-11e7-84b4-3a2822fe13a5.png)

**Comment by TaylorA-92** [comment]
Resolved in : https://github.com/kaytotes/NozdormuCore/pull/42/commits/fe0fe0234252484e85dc22875af8dd035f32d58a
