### ISSUE TITLE
Stormwind PvP Vendors

### ISSUE THREAD

**Issue by kaytotes** [kaytotes/NozdormuCore#35]
Need to remove the following NPC's

- [x] Harbinger Ennarth (Bring Back in TBC)
- [x] Knight-Lieutenant Moonstrike (Northrend Armor Quartermaster, Bring back with WotLK)
- [x] Lieutenant Tristia (Veteran Armor Quartermaster, Bring back with WotLK)
- [x] Captain Dirgehammer (Apprentice Armor Quartermaster, Bring back with WotLK)
- [x] Captain O'Neal (Jewelcrafting Quartermaster, Bring back with TBC)
- [x] Lieutenant Rachel Vaccar (Outland Armor Quartermaster, Bring back with TBC)

# Vendor Loot Tables

Todo: Research these.

**Comment by TaylorA-92** [comment]
Updated in https://github.com/kaytotes/NozdormuCore/pull/41/commits/c8016495db97adab7e9a22cbdc585b821570801f
