### ISSUE TITLE
Stormwind Battlemasters

### ISSUE THREAD

**Issue by kaytotes** [kaytotes/NozdormuCore#36]
The following Battlemasters need removing in Stormwind.

- [x] Beka Zipwhistle (Bring back in TBC)
- [x] Arcanist Paharin (Bring back in WotLK)

**Comment by TaylorA-92** [comment]
Updated in 
https://github.com/kaytotes/NozdormuCore/commit/27268d4e1772c978959c63bac8fe78e6b2f07ddb
